const { defineConfig } = require('vitest/config');

module.exports = defineConfig({
    test: {
        globals: true,
        testTimeout: 10000,
        hookTimeout: 30000,
        fileParallelism: false,
        maxWorkers: 1,
        isolate: false,
        include: [
            'test/unit/*.test.ts',
            'test/arc4.js',
            'test/protocol.js',
            'test/protocol20.js',
            'test/dpb-options.js',
            'test/srp.js',
            'test/service.js',
            'test/utf8-user-identification.js',
            'test/index.js',
            'test/promises.js',
            'test/cancel.js',
            'test/batch.js',
            'test/uri.js',
            'test/named-params.js',
            'test/returning-failure.js',
            'test/nest-tables.js',
            'test/type-cast.js',
            'test/statement-cache.js',
            'test/query-stream.js',
            'test/keepalive.js',
            'test/db-crypt-config.js',
            'test/encoding.js',
            'test/timezone.js',
            'test/decfloat.js',
            'test/mock-server.js',
            'test/pool-fixes.js',
            'test/pool-observability.js',
            'test/blob-chunks.js',
            'test/sql-schemas.js',
            'test/tablespaces.js',
            'test/json.js',
            'test/row-type.js',
            'test/collations.js'
        ],
    },
});
